name: Python application

on:
  schedule:
    - cron: '0 5 * * *'  # 9 AM UTC = 10 AM CET (winter time)
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Berlin

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    # - name: Restore state file
    #   uses: actions/cache@v4
    #   with:
    #     path: kaufda_state.json
    #     key: kaufda-state-${{ github.run_id }}
    #     restore-keys: kaufda-state-
    
    - name: Run offer checker
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        KEYWORDS: ${{ vars.KEYWORDS }}
        STATE_FILE: kaufda_state.json
      run: |
        python kaufda_alerts_version_cloud.py
