name: Python application

on:
  # Run daily at 10:00 AM CET (9:00 AM UTC in winter, 8:00 AM UTC in summer)
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC = 10 AM CET (winter time)
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run offer checker
      run: |
        python kaufda_alerts_version_cloud.py
